# Generated by Django 2.0.3 on 2019-07-09 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190709_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='İçerik'),
            preserve_default=False,
        ),
    ]
