# Generated by Django 2.0.3 on 2019-07-12 23:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoisePoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Seçenek')),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Soru')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.TimeField(default=datetime.timedelta(seconds=36000))),
            ],
            options={
                'get_latest_by': 'created_date',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'created_date'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Yorum Tarihi'),
        ),
        migrations.AddField(
            model_name='questionpoll',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='article.Article', verbose_name='Makale'),
        ),
        migrations.AddField(
            model_name='choisepoll',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choise', to='article.QuestionPoll'),
        ),
    ]
