# Generated by Django 2.0.3 on 2019-07-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190713_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choisepoll',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionpoll',
            name='article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': ['created_date'], 'ordering': ['-created_date']},
        ),
        migrations.DeleteModel(
            name='ChoisePoll',
        ),
        migrations.DeleteModel(
            name='QuestionPoll',
        ),
    ]
