# Generated by Django 2.0.3 on 2019-07-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190716_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='NabisCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncount', models.IntegerField(default=0, verbose_name='Nabis Sayaci')),
            ],
        ),
    ]
