# Generated by Django 2.0.3 on 2019-07-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_nabiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nabiscount',
            name='ncount',
            field=models.IntegerField(default=0),
        ),
    ]
